server:
#  port: 40010
  contextPath: /hspc-reference-api

spring:
  profiles:
    active: local
  resources:
    chain:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG

# Platform Servers
hspc:
  platform:
    api:
      security:
#        mode: secured
        mode: open
      oauth2:
        clientId: hspc_resource_server
        clientSecret: secret
        scopes: openid,launch,smart/orchestrate_launch
      fhir:
        db:
          driver: com.mysql.jdbc.Driver
          url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:hapi_pu}?autoReconnect=true
          username: ${MYSQL_USER:root}
          password: ${MYSQL_PASS:password}
          persistenceUnitName: ${MYSQL_PU:hapi_pu}
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        terminologyEndpointURL: fhir2.healthintersections.com.au/open
    authorization:
      url: http://localhost:8080/hspc-reference-authorization
      authorizeUrl: ${hspc.platform.authorization.url}/authorize
      tokenUrl: ${hspc.platform.authorization.url}/token
      tokenCheckUrl: ${hspc.platform.authorization.url}/introspect
      userinfoUrl: ${hspc.platform.authorization.url}/userinfo
      smart:
        launchUrl: ${hspc.platform.authorization.url}/Launch
        registrationEndpointUrl: ${hspc.platform.authorization.url}/register
        urisEndpointExtensionUrl: http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris
    messaging:
      url: http://localhost:8080/hspc-reference-messaging
      subscriptionSupport:
        enabled: true
        subscriptionEndpoint: ${hspc.platform.messaging.url}/subscription
        resourceEndpoint: ${hspc.platform.messaging.url}/resource

