mysql:
  image: "mysql:latest"
  environment:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "hapi_pu"
  ports:
   - 3306

api:
  build: .
  ports:
   - "9002:8080"
  environment:
    # MYSQL_HOST: "mysql"
    MYSQL_DB: "hapi_pu"
    MYSQL_PU: "hapi_pu"
  links:
    - "mysql:mysql"
